name: "Building Ren'Py Project"
author: 'SAn4Es_TV'
description: "Build your VN project using a specified Ren'Py SDK version"
inputs:
  sdk-version:
    description: "The version of the Ren'Py SDK to use"
    required: true
    default: '7.3.2'
  project-dir:
    description: "The path to the directory where the project exists"
    required: true
    default: '.'
  package:
    description: "Specific package to build for"
    required: false
    type: choice
    options:
      - pc
      - mac
      - linux
      - market
      - web
      - android
outputs:
  dir:
    description: "The directory where the distributed files exist"
  version:
    description: "The built version of the project"
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'gray-dark'
  icon: 'archive'
